### ISSUE TITLE
Keep the .gitkeep when remove models

### ISSUE THREAD

**Issue by wibimaster** [linto-ai/linto-platform-stack#1]
The script `get-models.sh` do a full `rm -r` of `$MODELS_FOLDER`.

But in case we clone this repository, models' folder contains a `.gitkeep`, and removing it creates a diff.

Moreover, error output shouldn't be hidden, I fell in the case I had

> rm: remove write-protected directory './models/[...]'?

for each subfolders dynamically created.

**Comment by damienlaine** [comment]
Greetings,

We're just about to release a new version of the LinTO Platform stack. This version will be enabled for production. Therefore, this get-models.sh script is obsolete and not maintened.
Please refer to the documentation to find and download models for our STT engine. : https://doc.linto.ai/#/services/linstt_download
