### ISSUE TITLE
Prise en main LinTO

### ISSUE THREAD

**Issue by ThomasDCepfl** [linto-ai/linto-platform-stack#11]
Bonjour,

Nous avons été en contact récemment, dans le cadre d'une démarche d'innovation en entreprise.

Après la mise en place d'une VM Linux Debian, j'ai pu tenter une installation de LinTO en suivant vos tutoriels détaillés.
J'ai opté pour une installation mono-host pour commencer et suis parvenu à accéder à la plateforme LinTO admin en local. J'ai alors pu créer un service de transcription grâce au STT-Manager et adapter mon application avec le Worflow.
En revanche, quand j'ai voulu tester ce service en essayant le Speech-to-text du STT-Manager. Je reçois alors une erreur 404 disant que cette partie de la plateforme "/stt/{serviceID}/transcribe" n'existe pas.
Auriez-vous une idée de l'origine de ce problème et éventuellement un moyen de le résoudre ?

Je précise que je n'ai pas essayé de connecter de client, jugeant que je pouvais utiliser LinTO sans pour commencer. Je n'ai également rien changé au fichier .dockerenv, car les variables me paraissaient correctement initialisées. Peut-être faut-il adapter ces "mandatory variables" que vous évoquez ? Si oui, quelles sont-elles et comment les adapter à mon cas d'usage ?
Il y a également quelques nodes qui fail, comme ceux liés au service platform-mongo-setup, et le certificat construit avec "mkcert" ne semble pas être fonctionnel.

Bien à vous,
Thomas de Chevigny

**Comment by damienlaine** [comment]
Bonjour
Vous rien changé au fichier .dockerenv ? Cela me semble impossible pour avoir une stack fonctionnelle, j'imagine que vous avez fait quelques modifications tout de même. Il faudrait vérifier cela.
Pour le service de transcription, si vous avez une 404, soit le service n'est pas démarré, soit vous n'avez pas utilisé la case "external access" lors de la création du service sur le client Swagger de STT-Services-Manager. Dans ce cas de figure (API de transcription utilisable directement, hors d'application LinTO créées sur la plateforme d'admin via un client LinTO) il faut ouvrir la route correspondante avec l'option "external access"

Contactez moi sur dlaine@linagora.com si vous voulez qu'on regarde ensemble plus avant les paramétrages spécifique de votre environnement.
Cordialement,

**Comment by phil-neuronys** [comment]
Bonsoir @damienlaine
Nous avons à peu près le même problème.
Nous avons réussi à intaller LinTO et demander une transcription d'un fichier WAV par un POST vers l'API
Parallèment, nous avons réussi à installer Jitsi, mais impossible de faire communiquer les 2, comme votre video (https://www.youtube.com/watch?v=u1je0h29grg).
Nous sommes même reparti de la branche next pour creuser davantage. Lorsqu'on active la transcription, Jitsi nous dit qu'elle sera disponible à tel endroit, mais rien et surtout aucun affichage de sous-titre.
Où devons nous investiguer ?
Puis-je me permettre de vous envoyer par email nos fichiers de config ?
D'avance un grand merci pour votre aide
Philippe

**Comment by damienlaine** [comment]
Bonsoir,
En utilisant Linto-platform-stack vous avez besoin de lancer un service qui est une version customisée de jigasi : avez-vous regardé là https://github.com/linto-ai/linto-jitsi ?

**Comment by phil-neuronys** [comment]
Merci @damienlaine 
Nous testerons cela dès lundi :-)
Bon weekend
