### ISSUE TITLE
Accéder aux services de linTo après installation

### ISSUE THREAD

**Issue by dialloDioulde** [linto-ai/linto-platform-stack#15]
Bonjour, 
J'ai installé linTo sur une VM Debian en respectant toutes les règles d'installation indiquées sur la documentation, mais quand je fais docker ps : 
Parfois je vois l'ensemble des éléments du stack linTo.
Parfois le Mongo DB qui n'est pas dans la liste.
Parfois c'est le STT qui n'est pas dans la liste.

Et quand je tape docker logs (id mongodb) je vois le message suivant : waiting for startup ...

Et aussi je n'arrive pas à accéder aux services de linTo en tapant  dev.linto.local sur mon navigateur. 

Merci d'avance !

**Comment by Houpert** [comment]
Bonjour

Je recommanderais d'utiliser plutôt `docker service ls` dans un environnement de stack pour voir les services qui ne sont pas démarré, serait t'il possible d'avoir les traces de celui-ci et d'avoir leur logs des replicas qui ne tourne pas : `docker service logs nom_du_service`. (A noter que les services mongo-setup et mongo-migration ce stop automatiquement)

Concernant le `waiting for startup` serait t'il possible d'avoir plus d'information ? Dans la stack il y a plusieurs images mongo.

Pour **dev.linto.local** avez vous bien modifié le fichier `/etc/hosts` ? Configuré la variable d’environnement **LINTO_STACK_DOMAIN** ?

Cordialement

**Comment by dialloDioulde** [comment]
Re-Bonjour, 
Merci pour votre réponse.

Voici ce que j'ai quand je tape docker service logs : 
![Capture d’écran (42)](https://user-images.githubusercontent.com/60967220/112808140-f8d33a80-9078-11eb-8273-df13924af51e.png)

Non je n'ai pas touché au fichier /etc/hosts, qu'est ce que je dois écrire dedans ? 
Oui j'ai bien configuré le .dockerenv en complétant le LINTO_STACK_DOMAIN. 

Merci d'avance !

**Comment by Houpert** [comment]
Bonjour

Il y a bien un problème dans votre instance, vous avez du louper une étape, je vous redirige vers le site linto :
[stack-deployment](https://doc.linto.ai/#/stack/stack?id=linto-stack-deployment-tool) 

Concernant le **etc/hosts** il faudrait ajouter ceci dans le fichier : `127.0.0.1	 dev.linto.local`

Cordialement

**Comment by dialloDioulde** [comment]
Re-Bonjour, 
merci pour votre réponse. 

Une dernière question svp, dans la commande suivante docker node update --label-add ip=ingress {Hostname_Of_The_Node_In_Your_Swarm_Cluster} est ce que c'est l'IP de mon ordinateur Windows qu'il faut mettre ou celle de la VM Debian ? 

Merci d'avance !

**Comment by Houpert** [comment]
Bonjour,

Vous devez pouvoir récupérer le hostname dans la première étapes. [doc.linto](https://doc.linto.ai/#/stack/stack?id=ready-lets-deploy-linto-platform-)

Cordialement

**Comment by damienlaine** [comment]
Bonjour,
Nous avons déjà fait un call avec vous concernant vos cas d'usages finaux (NLP / Transcription / TTS en local sur un téléphone Android) et ils semblent éloignés de ce que nous proposons. Pour un accompagnement et une assistance dédiée, je vous remercie de prendre contact avec nous sur contact@linto.ai . Le reste est dans la documentation doc.linto.ai.
Bien cordialement,
