### ISSUE TITLE
LINTO HTTP-404 error: TOCK 21.3.0 seems to have a new REST API entry point

### ISSUE THREAD

**Issue by pandorino70** [linto-ai/linto-platform-stack#17]
Dear team
I installed LINTO in a test environment because curious to verify its capabilities.
Followed all the very precise steps described in your guide, and installation was successful.

I was able to access to the admin interface. However, when tried to access to the "tock interface", 
I always got the error "Cannot connect Tock interace". 

In the logs of the linto_stack_linto-platform-admin container, the following HTTP-404 error was tracked:
####################################
Error: Request failed with status code 404
    at createError (/usr/src/app/linto-admin/webserver/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/src/app/linto-admin/webserver/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/src/app/linto-admin/webserver/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1252:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  config: {
    url: 'http://linto-tock-nlu-web:8080/rest/admin/applications',
[...]
####################################

After several attempts, the latest thing I did was to modify, into the .dockerenv file, the default value of 
"LINTO_STACK_TOCK_TAG=21.3.0" 

into

"LINTO_STACK_TOCK_TAG=20.9.3"

redeployed everything with the --force-pull option, and everything worked like a charm!!

I may conclude that the new version of tock (at least 21.3.0 which is the default proposed into the docker template file) has changed the API (or the URI to call it).  Probably the same also for the tock-admin and tock-bot APIs.

Can you confirm my supposition?
If confirmed, is there any way to solve the issue to make LINTO working also with the new versions of tock?  Otherwise, in the current LINTO version, the LINTO_STACK_TOCK_TAG must be set to 20.9.3 by default replacing 21.3.0.

Kind regards
Mauro

**Comment by Houpert** [comment]
Hello,

Then it will be possible with the next release (env var  `LINTO_STACK_TOCK_BASEHREF`)

Kind regards
Houpert
