### ISSUE TITLE
Transcribe 404 error

### ISSUE THREAD

**Issue by rqueraud** [linto-ai/linto-platform-stack#20]
Hi,

I deployed the stack and tried to create a STT service on the swagger page.

I think I managed to create one, but when I make a POST query to 
**​/stt​/testServiceId_cmd_language_and_acoustic​/transcribe**, this lead me to a 404 error.

Something that I don't undestand is that when I make a GET query on the 
**​/stt-manager​/service​/testServiceId_cmd_language_and_acoustic** endpoint, the "isOn" property is set to 0.

```json
{
  "status": "success",
  "data": {
    "_id": "61af543cbdcb72002e11738a",
    "serviceId": "testServiceId_cmd_language_and_acoustic",
    "tag": "online",
    "replicas": 1,
    "LModelId": "decoding_cmd_with_acoustic",
    "AModelId": "french_acoustic",
    "externalAccess": 0,
    "lang": "fr-FR",
    "isOn": 0,
    "date": "12/07/2021-14:34:11"
  }
}
```
Thanks in advance for your help.

Regards

**Comment by damienlaine** [comment]
Hello,

Please have a look to : 
Service Runtime APIs --> /stt-manager/service/{serviceId}/start
And also /stt-manager/services/running

You might need to --> /stt-manager/langmodel/{modelId}/generate/graph before you start any services.

Final words, as you defined NO external access on this transcription service you won't be able to post anything to it unless you're within the Docker network.
