### ISSUE TITLE
Error: network "linto-net" is declared as external, but could not be found. You need to create a swarm-scoped network before the stack is deployed

### ISSUE THREAD

**Issue by hassanayoub1985** [linto-ai/linto-platform-stack#24]
Hello,
I am trying to install linto on a VPS to tryit first before taking decistion to try it it on a real infrastructure, but it I have a problem.
After the preparation on of a mono host,and clonning the script, i tried the ./start.sh but I am facing this error. Any idea how to fix it?

root@ubuntu-s-4vcpu-8gb-intel-blr1-01:~# cd linto-platform-stack/
root@ubuntu-s-4vcpu-8gb-intel-blr1-01:~/linto-platform-stack# ./start.sh
Generating configuration file in /root/linto_shared_mount/
SSL : ON
Request for let's encrypt certs for r0b0tik.online : ON
HTTP Basic Auth : OFF
MQTT Login : ON
network "linto-net" is declared as external, but could not be found. You need to create a swarm-scoped network before the stack is deployed

**Comment by damienlaine** [comment]
https://doc.linto.ai/docs/developpers/agent/server/stack_deploy#ready--lets-deploy-linto-platform-
