### ISSUE TITLE
Some containers cannot start

### ISSUE THREAD

**Issue by jbleduigou** [linto-ai/linto-platform-stack#4]
Hi,

I have been trying to start the platform stack using the provided docker-compose files.
Unfortunately the following containers do not seem to start:
 * linto-platform-admin
 * linto-stt-worker-fr
 * linto-stt-worker-en

This is what the log output shows:

```
> docker logs linto-platform-admin
Missing LINTO_STACK_DOMAIN
```

```
> docker logs linto-stt-worker-en 
Traceback (most recent call last):
  File "/usr/lib/python3.5/configparser.py", line 1135, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'decoder_params'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./worker_offline.py", line 40, in <module>
    DECODER_SYS = decoder_settings.get('decoder_params', 'decoder')
  File "/usr/lib/python3.5/configparser.py", line 778, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.5/configparser.py", line 1138, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'decoder_params'


```

It seems to me that some environment variables are not properly populated.
My understanding is that the Docker images have been slightly modified in the last couple of months.
The docker compose files however have not been updated recently.

**Comment by damienlaine** [comment]
You're right, we've been through a massive rework of the complete stack the last 5 months.

This work will get available by next week in this repo. Maybe things shall still break-up though.

Until that, you might still build your docker images from the repos, try our docker image independently  and figure-out what's going on with the env vars.

Sorry for the temporary inconvenience. Stay tuned and expect us ! I'll close this issue when everything's ready.

**Comment by jbleduigou** [comment]
Hi @damienlaine,

Thanks a lot for your quick reply!

**Comment by damienlaine** [comment]
Greetings,

Here you go, we just published the Docker Swarm stack deployment tool with a lot of explanations.

Hope that helps...
